config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "estimates#index"
  resources :estimates do
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show,:edit,:update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  belongs_to :user
  has_many :images,dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
 
 extend ActiveHash::Associations::ActiveRecordExtensions
 belongs_to_active_hash :probability
 belongs_to_active_hash :status

  with_options presence: true do
    validates :customer
    validates :get
    validates :deadline
    validates :name
    validates :figure_number
    validates :make
    validates :metal
    validates :quantity
    validates :sell_price
    validates :purchase_price
    validates :profit
    validates :sell_price_total
    validates :profit_total
    validates :probability_id
    validates :status_id
  end

  scope :estimate, -> { order("created_at DESC")} 

end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :estimate,optional: true
  mount_uploader :image, ImageUploader
end

app/models/probability.rb
class Probability < ActiveHash::Base
  self.data = [
  {id: 1, name: "A(81〜100%)"},
  {id: 2, name: "B(61〜80%)"},
  {id: 3, name: "C(41〜60%)"},
  {id: 4, name: "D(21〜40%)"},
  {id: 5, name: "E(0〜20%)"},
  {id: 6, name: "その他"}
  ]
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    {id: 1, name: "交渉中"},
    {id: 2, name: "受注"},
    {id: 3, name: "失注"},
    {id: 4, name: "試作"},
    {id: 5, name: "開発段階"},
    {id: 6, name: "参考見積り"},
    {id: 7, name: "その他"},
  ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: true
  has_many :estimates
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:company_name])
  end
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :authenticate_user!,  except:[:index]
  before_action :set_estimate, only: [:show, :edit, :update, :destroy]

  def index
    @estimate = Estimate.new
  end

  def new
    @estimates = Estimate.includes(:user).estimate.page(params[:page]).per(6)
    @numbers = Estimate.count(:id)
    @sell_price_totals = Estimate.sum(:sell_price_total)
    @profit_totals = Estimate.sum(:profit_total)
  end

  def create
    @estimate = Estimate.new(estimate_params)
    if @estimate.save
      redirect_to new_estimate_path
    else
      render :index
    end
  end

  def show
  end

  def edit
  end

  def update
    if @estimate.update(estimate_params)
      redirect_to new_estimate_path(@estimate)
    else
      render :edit
    end
  end

  def destroy
   if @estimate.destroy
    redirect_to root_path
   else
    render :index
   end
  end

  def search
    @estimates = Estimate.search(params[:search])
    @q = Estimate.ransack(params[:q])
    @search_estimate = Estimate.ransack(params[:q]) 
    @result = @search_estimate.result.page(params[:page])
  end

  private 
  def estimate_params
    params.require(:estimate).permit(:customer,:get,:deadline,:name,:figure_number,:make,:metal,:start, :use, :quantity, :sell_price, :purchase_price, :profit, :sell_price_total, :profit_total, :remark, :probability_id, :status_id, images_attributes: [:image,:id,:_destroy]).merge(user_id: current_user.id)
  end

  def set_estimate
    @estimate = Estimate.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only:[:show, :edit, :upadate, :destroy]

  def show
    @estimates = @user.estimates.estimate.page(params[:page]).per(6)
    @number = @user.estimates.count(:id)
    @sell_price_total = @user.estimates.sum(:sell_price_total)
    @profit_total = @user.estimates.sum(:profit_total)
  end

  def update
    if current_user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :company_name)
  end
  
  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_has?(instance)
    user_signed_in? && current_user == instance.user
  end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
  def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}円"
  end
end

app/views/estimates/_estimate_box.html.haml
%table.estimate-new-box{:border => "2"}
  %tr
    %th{:width => "270"} 品名
    %th{:width => "600"}
      =estimate.name
  %tr
    %th 図番  
    %th
      =estimate.figure_number
  %tr
    %th 入手日
    %th
      =estimate.get.strftime("%Y-%m-%d")
  %tr
    %th 期限
    %th
      =estimate.deadline.strftime("%Y-%m-%d")
  %tr
    %th 見積状況
    %th
      =estimate.status.name
  %tr
    %th 受注確率
    %th
      =estimate.probability.name

app/views/estimates/_estimate_form.html.haml
.main_estimate__container-1
  =f.label :品名 ,class:"main_estimate__container-1__get-label"
  =f.label :必須  ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :name ,class:"main_estimate__container-1__get-container"
  =f.label :図番 ,class:"main_estimate__container-1__get-label"
  =f.label :必須  ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :figure_number ,class:"main_estimate__container-1__get-container"
  =f.label :入手日 ,class:"main_estimate__container-1__get-label"
  =f.label :必須  ,class:"main_estimate__container-1__get-need-label"
  =f.date_field :get ,class:"main_estimate__container-1__get-container"
  =f.label :締切 ,class:"main_estimate__container-1__get-label"
  =f.label :必須  ,class:"main_estimate__container-1__get-need-label"
  =f.date_field :deadline ,class:"main_estimate__container-1__get-container"
  =f.label :客先 ,class:"main_estimate__container-1__get-label"
  =f.label :必須  ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :customer ,class:"main_estimate__container-1__get-container"
.main_estimate__container-2
  =f.label :工法 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :make ,class:"main_estimate__container-1__get-container"
  =f.label :材質 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :metal ,class:"main_estimate__container-1__get-container"
  =f.label :SOP ,class:"main_estimate__container-1__get-label"
  =f.label :任意 ,class:"main_estimate__container-1__get-free-label"
  =f.date_field :start ,class:"main_estimate__container-1__get-container"
  =f.label :使用用途 ,class:"main_estimate__container-1__get-label"
  =f.label :任意 ,class:"main_estimate__container-1__get-free-label"
  =f.text_field :use ,class:"main_estimate__container-1__get-container"
  =f.label :数量 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.number_field :quantity ,id:"quantity",class:"main_estimate__container-1__get-container"
.main_estimate__container-3
  =f.label :売り単価 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :sell_price ,id:"sell_price",class:"main_estimate__container-1__get-container"
  =f.label :仕入れ単価 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :purchase_price ,id:"purchase_price",class:"main_estimate__container-1__get-container"
  =f.label :利益 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :profit, id:"profit" ,class:"main_estimate__container-1__get-container"
  =f.label :売上合計 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :sell_price_total, id:"sell_price_total" ,class:"main_estimate__container-1__get-container"
  =f.label :利益合計 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :profit_total, id:"profit_total" ,class:"main_estimate__container-1__get-container"
.main_estimate__container-4
  =f.label :資料 ,class:"main_estimate__container-1__get-label"
  =f.label :任意 ,class:"main_estimate__container-1__get-free-label"
  .prev-content
  .label-content
    = f.label :"images_attributes_0_image",class: "label-box",id: "label-box--#{@estimate.images.length}" do
      %pre.label-box__text-visible ファイルを選択をクリックしてアップロード
  .hidden-content
    = f.fields_for :images do |i|
      = i.file_field :image, class: "hidden-field", id: "estimate_images_attributes_0_image"
    - @estimate.images.length.upto(4) do |i|
      %input{name: "estimate[images_attributes][#{i}][image]", id: "estimate_images_attributes_#{i}_image", class:"hidden-field", type:"file"}
  =f.label :受注確率 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.collection_select :probability_id, Probability.all, :id, :name, {prompt: "選択してください"},class:"main_estimate__container-1__get-container"
  =f.label :見積状況 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.collection_select :status_id, Status.all, :id, :name, {prompt: "選択してください"},class:"main_estimate__container-1__get-container"
  =f.label :備考 ,class:"main_estimate__container-1__get-label"
  =f.label :任意 ,class:"main_estimate__container-1__get-free-label"
  =f.text_field :remark, id:"profit" ,class:"main_estimate__container-1__get-container"
  =f.submit "送信する",class: "main_estimate__container-1__sumbit",data: { confirm: "送信しますか？" }

app/views/estimates/_estimate_new.html.haml
.new-estimate__box-1__container
  =estimate.user.name
  - if current_user_has?(estimate)
    =link_to "編集", edit_estimate_path(estimate.id),class:"new-estimate__box-1__container__edit"
    =link_to "削除", estimate_path(estimate.id), method: :delete,data: { confirm: "削除しますか？" },class:"new-estimate__box-1__container__delete"
  - if user_signed_in?
    =link_to "詳細", estimate_path(estimate.id),class:"new-estimate__box-1__container__show"

app/views/estimates/_header.html.haml
.header 
 %p MitsuMane

app/views/estimates/_main_estimate.html.haml
.main_estimate
  - if user_signed_in?
    =form_for [@estimate] do |f|
      = render 'layouts/error_messages', model: f.object
      = render partial: "estimate_form", locals: { f: f}
  - else
    = form_for [@estimate] do |f|
      = render partial: "not-estimate_form", locals: { f: f}

app/views/estimates/_menubar.html.haml
.menubar
 .menubar__home
  =link_to "HOME", root_path
 .menubar__mypage
  - if user_signed_in?
   =link_to "マイページ", user_path(current_user)
   .menubar__estimate
    =link_to "見積り一覧", new_estimate_path
   .menubar__search
    =link_to "検索", search_estimates_path
  - else 
    .menubar__mypage__new
    =link_to "新規登録", new_user_registration_path
    .menubar__mypage__login
    =link_to "ログイン", new_user_session_path

 

app/views/estimates/_not-estimate_form.html.haml
.main_estimate__container-1
  =f.label :品名 ,class:"main_estimate__container-1__get-label"
  =f.label :必須  ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :name ,class:"main_estimate__container-1__get-container"
  =f.label :図番 ,class:"main_estimate__container-1__get-label"
  =f.label :必須  ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :figure_number ,class:"main_estimate__container-1__get-container"
  =f.label :入手日 ,class:"main_estimate__container-1__get-label"
  =f.label :必須  ,class:"main_estimate__container-1__get-need-label"
  =f.date_field :get ,class:"main_estimate__container-1__get-container"
  =f.label :締切 ,class:"main_estimate__container-1__get-label"
  =f.label :必須  ,class:"main_estimate__container-1__get-need-label"
  =f.date_field :deadline ,class:"main_estimate__container-1__get-container"
  =f.label :客先 ,class:"main_estimate__container-1__get-label"
  =f.label :必須  ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :customer ,class:"main_estimate__container-1__get-container"
.main_estimate__container-2
  =f.label :工法 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :make ,class:"main_estimate__container-1__get-container"
  =f.label :材質 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :metal ,class:"main_estimate__container-1__get-container"
  =f.label :SOP ,class:"main_estimate__container-1__get-label"
  =f.label :任意 ,class:"main_estimate__container-1__get-free-label"
  =f.date_field :start ,class:"main_estimate__container-1__get-container"
  =f.label :使用用途 ,class:"main_estimate__container-1__get-label"
  =f.label :任意 ,class:"main_estimate__container-1__get-free-label"
  =f.text_field :use ,class:"main_estimate__container-1__get-container"
  =f.label :数量 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.number_field :quantity ,id:"quantity",class:"main_estimate__container-1__get-container"
.main_estimate__container-3
  =f.label :売り単価 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :sell_price ,id:"sell_price",class:"main_estimate__container-1__get-container"
  =f.label :仕入れ単価 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :purchase_price ,id:"purchase_price",class:"main_estimate__container-1__get-container"
  =f.label :利益 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :profit, id:"profit" ,class:"main_estimate__container-1__get-container"
  =f.label :売上合計 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :sell_price_total, id:"sell_price_total" ,class:"main_estimate__container-1__get-container"
  =f.label :利益合計 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.text_field :profit_total, id:"profit_total" ,class:"main_estimate__container-1__get-container"
.main_estimate__container-4
  =f.label :受注確率 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.collection_select :probability_id, Probability.all, :id, :name, {prompt: "選択してください"},class:"main_estimate__container-1__get-container"
  =f.label :見積状況 ,class:"main_estimate__container-1__get-label"
  =f.label :必須 ,class:"main_estimate__container-1__get-need-label"
  =f.collection_select :status_id, Status.all, :id, :name, {prompt: "選択してください"},class:"main_estimate__container-1__get-container"
  =f.label :備考 ,class:"main_estimate__container-1__get-label"
  =f.label :任意 ,class:"main_estimate__container-1__get-free-label"
  =f.text_field :remark, id:"profit" ,class:"main_estimate__container-1__get-container"

app/views/estimates/_search_form.html.haml
.search-main__left
  =search_form_for(@q, url: search_estimates_path) do |f|
    .search-main__left__search_sort
      =f.select( :sorts, { '並び替え': 'id desc', "数量の少ない順": "quantity desc","数量の多い順": "quantity asc","単価の安い順": "sell_price asc", "単価の高い順": "sell_price desc", "利益の低い順": "profit desc","利益の多い順": "profit desc","締め切り順": "deadline asc", "入手順": "get desc", "SOPの早い順": "start desc"}, {onchandge: "this.form.submit()"},class: "search-main__left__search_sort__box")
    .search-main__left__search_form
      .search-main__left__search_form__title
        詳細検索
      .search-main__left__search_form__name-title
        商品名で検索
      .search-main__left__search_form__name
      =f.search_field :name_cont, placeholder: "商品名", class:"search-main__left__search_form__name_box"
      .search-main__left__search_form__figure_number-title
        図番で検索
      .search-main__left__search_form__figure_number
      =f.search_field :figure_number_cont, placeholder: "図番", class:"search-main__left__search_form__figure_number_box"
      .search-main__left__search_form__customer-title
        客先名
      .search-main__left__search_form__customer
      =f.search_field :customer_cont, placeholder: "客先名", class:"search-main__left__search_form__customer_box"
      .search-main__left__search_form__make-title
        工法
      .search-main__left__search_form__make
      =f.search_field :make_cont, placeholder: "工法", class:"search-main__left__search_form__make_box"
      .search-main__left__search_form__metal-title
        材質
      .search-main__left__search_form__metal
      =f.search_field :metal_cont, placeholder: "材質", class:"search-main__left__search_form__metal_box"
      .search-main__left__search_form__use-title
        使用用途
      .search-main__left__search_form__use
      =f.search_field :use_cont, placeholder: "使用用途", class:"search-main__left__search_form__use_box"
      .search-main__left__search_form__price-title
        売上単価
      .search-main__left__search_form__price-box
        =f.search_field :sell_price_gteq, placeholder: "￥ Min",class:"search-main__left__search_form__price-box__box1"
        %span{class:'search-main__left__search_form__price-box__box3'} 〜
        =f.search_field :sell_price_lteq, placeholder: "￥ Max",class:"search-main__left__search_form__price-box__box2"
      .search-main__left__search_form__status-title
        見積りの状況
      .search-main__left__search_form__status
      = f.collection_select :status_id_eq, Status.all, :id, :name, {prompt: "選択してください"},class:"search-main__left__search_form__status_box"
      .search-main__left__search_form__probability-title
        受注確率
      .search-main__left__search_form__probability
      = f.collection_select :probability_id_eq, Probability.all, :id, :name, {prompt: "選択してください"},class:"search-main__left__search_form__probability_box"
      .search-main__left__search_form__btn-box
        =f.button "クリア", type: :reset, class:"search-main__left__search_form__btn-box__box"
        =f.submit "完了", class:"search-main__left__search_form__btn-box__submit"

app/views/estimates/edit.html.haml
=render "header"
=render "menubar"
.main_estimate
  =form_for [@estimate] do |f|
    =render partial: "estimate_form", locals:{f: f}

app/views/estimates/index.html.haml
.wrapper
  = render "header"
  = render "menubar"
  = render "main_estimate"

app/views/estimates/new.html.haml
= render "header"
= render "menubar"
= paginate(@estimates)
.new-estimate
  .new-estimate__left
    .new-estimate__left__box
      .new-estimate__left__box__estimate
        見積り件数
        %br/
        ="#{@numbers}件"
      .new-estimate__left__box__sell
        売上合計
        %br/
        = converting_to_jpy(@sell_price_totals)
      .new-estimate__left__box__profit
        利益合計
        %br/
        = converting_to_jpy(@profit_totals)

  .new-estimate__right
    -@estimates.each do |estimate|
      .new-estimate__box-1
        =render partial: "estimate_new", locals:{estimate: estimate}
        .new-estimate__box1__negotiation
          = render partial: "estimate_box", locals:{estimate: estimate}
      

app/views/estimates/search.html.haml
= render "header"
= render "menubar"
.search-main
  =render "search_form"
  .search-main__right
    .search-main__right__title
      検索結果
      .search-main__right__box
        = paginate(@result)
        -unless @result.empty?
          .search-main__right__box__estimate
            -@result.each do |estimate|
              .search-main__right__box__estimate__estimate-box
                = render partial: "estimate_new", locals:{estimate: estimate}
                = render partial: "estimate_box", locals:{estimate: estimate}
        -else
          .search-main__right__non
            %p 検索結果に該当する見積りはありません

app/views/estimates/show.html.haml
= render "header"
= render "menubar"
.show-estimate
  見積り詳細
%table.show-estimate__show-box{:border => "2"}
  %tr
    %th{:width => "270"} 品名
    %th{:width => "600"}
      =@estimate.name
  %tr
    %th 図番  
    %th
      =@estimate.figure_number
  %tr
    %th 入手日
    %th
      =@estimate.get.strftime("%Y-%m-%d")
  %tr
    %th 期限
    %th
      =@estimate.deadline.strftime("%Y-%m-%d")
  %tr
    %th 見積状況
    %th
      =@estimate.status.name
  %tr
    %th 受注確率
    %th
      =@estimate.probability.name
  %tr
    %th 客先
    %th
      =@estimate.customer
  %tr
    %th 工法
    %th
      =@estimate.make
  %tr
    %th 材質
    %th
      =@estimate.metal
  %tr
    %th SOP
    %th
      -if @estimate.start.present?
        =@estimate.start.strftime("%Y-%m-%d")
      -else
  %tr
    %th 使用用途
    %th
      =@estimate.use
  %tr
    %th 数量/月
    %th
      =@estimate.quantity
  %tr
    %th 売り単価
    %th
      =converting_to_jpy(@estimate.sell_price)
  %tr
    %th 仕入れ単価
    %th
      =converting_to_jpy(@estimate.purchase_price)
  %tr
    %th 利益
    %th
      =converting_to_jpy(@estimate.profit)
  %tr
    %th 売上合計
    %th
      =converting_to_jpy(@estimate.sell_price_total)
  %tr
    %th 利益合計
    %th
      =converting_to_jpy(@estimate.profit_total)
  %tr
    %th 備考
    %th
      =@estimate.remark

app/views/layouts/_error_messages.html.haml
-if model.errors.any? 
  .alert
    %ul
      -model.errors.full_messages.each do |message| 
        %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Mitsumane2
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/users/_menubar.haml.haml
.menubar
 .menubar__home
  =link_to "HOME", root_path
 .menubar__mypage
  =link_to "ログアウト", destroy_user_session_path, method: :delete
 .menubar__estimate
  =link_to "Update", edit_user_path(current_user)

app/views/users/_menubar.html.haml
.menubar
 .menubar__home
  =link_to "HOME", root_path
 .menubar__mypage
  =link_to "ログアウト", destroy_user_session_path, method: :delete
 .menubar__estimate
  =link_to "Update", edit_user_path(current_user)

app/views/users/edit.html.haml
=render "estimates/header"
=render "estimates/menubar"
.login-main
  .login-main__title
    アカウント編集
  .login-main__box
    = form_for(current_user) do |f|
      .login-main__box__field
        = f.label :名前　,class: "login-main__box__field__label"
        %br/
        = f.text_field :name, autofocus: true,class: "login-main__box__field__contanir"
      .login-main__box__field
        = f.label :メールアドレス,　class: "login-main__box__field__label"
        %br/
        = f.email_field :email, autofocus: true, autocomplete: "email",class: "login-main__box__field__contanir"
      .login-main__box__field
        = f.label :会社名,class: "login-main__box__field__label"
        %br/
        = f.text_field :company_name, autofocus: true,class: "login-main__box__field__contanir"
      .login-main__box__field
        = f.submit "Update",class: "login-main__box__field__submit"
      .login-main__box__field
        =link_to "トップページに戻る", root_path

app/views/users/show.html.haml
=render "estimates/header"
=render "menubar"
= paginate(@estimates)
.show-mypage
  .show-mypage__left
    .show-mypage__left__box
      .show-mypage__left__box__user
        ユーザー
        %br/
        = current_user.name
      .show-mypage__left__box__estimate
        見積り件数
        %br/
        ="#{@number}件"
      .show-mypage__left__box__sell-price
        売上合計
        %br/ 
        = converting_to_jpy(@sell_price_total)
      .show-mypage__left__box__profit
        利益合計
        %br/ 
        = converting_to_jpy(@profit_total)

  .show-mypage__right
    -@estimates.each do |estimate|
      - if current_user_has?(estimate)
        .show-mypage__box
          .show-mypage__box__container1
            =render partial: "estimates/estimate_new", locals:{estimate: estimate}
          .show-mypage__box__container2
            %table.estimate-user-box{:border => "2"}
              %tr
                %th{:width => "170"} 品名
                %th{:width => "300"}
                  =estimate.name
              %tr
                %th 図番  
                %th
                  =estimate.figure_number
              %tr
                %th 入手日
                %th
                  =estimate.get.strftime("%Y-%m-%d")
              %tr
                %th 期限
                %th
                  =estimate.deadline.strftime("%Y-%m-%d")
              %tr
                %th 見積状況
                %th
                  =estimate.status.name
              %tr
                %th 受注確率
                %th
                  =estimate.probability.name